### PR TITLE
Fix doesn't work with Ruby < 2.4

### LINKED ISSUE #5: Doesn't work with Ruby < 2.4
I added `gem 'xipio'` in my Gemfile and got the below error when accessed to the root URL.

```
NoMethodError: undefined method `match?' for "my-app.192.168.0.109.xip.io":String
Did you mean?  match
~/git/github.com/Fablic/fril_web/vendor/bundle/ruby/2.3.0/gems/xipio-1.0.1/lib/xipio/middleware.rb:8:in `call'
~/git/github.com/Fablic/fril_web/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
~/git/github.com/Fablic/fril_web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/engine.rb:518:in `call'
~/git/github.com/Fablic/fril_web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/application.rb:165:in `call'
~/git/github.com/Fablic/fril_web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/railtie.rb:194:in `public_send'
~/git/github.com/Fablic/fril_web/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/railtie.rb:194:in `method_missing'
~/git/github.com/Fablic/fril_web/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
~/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:155:in `handle'
~/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:109:in `rescue in block (2 levels) in start'
~/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:106:in `block (2 levels) in start'
~/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:96:in `each'
~/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:96:in `block in start'
~/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:76:in `loop'
~/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:76:in `start'
~/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:12:in `run'
~/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/bin/nack_worker:4:in `<main>'
```

I rewrote `xipio/middleware.rb` as below and it resolved the error.

```diff
diff --git a/lib/xipio/middleware.rb b/lib/xipio/middleware.rb
index 960f8e5..ec592e5 100644
--- a/lib/xipio/middleware.rb
+++ b/lib/xipio/middleware.rb
@@ -5,7 +5,7 @@ module Xipio
     end
 
     def call(env)
-      tld_length = env['HTTP_HOST'].match?(/\.xip\.io(:\d{1,5})?\z/) ? 6 : 1
+      tld_length = env['HTTP_HOST'].match(/\.xip\.io(:\d{1,5})?\z/) ? 6 : 1
       ActionDispatch::Http::URL.tld_length = tld_length
       @app.call(env)
     end
```

Let me know if this is the correct solution.

Thanks.

### PR DESCRIPTION
**Pull request by hkurokawa**
# Issue
Closes #5

# Changes
- Use `=~` instead of `match?` for investigating `env['HTTP_HOST']`

# Note
Ruby 2.4 introduced `String#match?` method which returns `true/false` instead of the match data and it would be better to use the method if we do not support Ruby < 2.4.  Another solution is just using `/.../ =~ env['HTTP_POST']`.

See https://github.com/fphilipe/xipio/pull/4#discussion_r151167542

### CODE REVIEW

**Comment by fphilipe** [comment]
Thanks! New version released.

**Comment by hkurokawa** [comment]
Thanks! Appreciate your efficient work!
